version: '2'

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - 4444:4444
        #device_041604952fb8090222222:
        #image: nesh/device_with_appium:1.5
        #restart: unless-stopped
        # depends_on:
        # - selenium_hub
        # ports:
        # - 4743:4723
        # privileged: true
        # volumes:
        #      - ~/.android:/root/.android
        # environment:
        #- PUBLIC_IP=${PUBLIC_IP}     
        # - STF_TOKEN=${STF_TOKEN}    
        #      - CONNECT_TO_GRID=true
        #      - SELENIUM_HOST=selenium_hub
        #      - REMOTE_ADB=true 
        #      - ANDROID_DEVICES=041604952fb809022222
        #      - REMOTE_ADB_POLLING_SEC=60
  device_041604952fb80902:
    image: nesh/device_with_appium:2.1      
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4733:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=041604952fb80902
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true

  device_HEKNU19304105657:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4743:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=HEKNU19304105657
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true        

  device_CLCDU19314001285:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4753:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=CLCDU19314001285
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true        

  device_3ST0219319000137:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4763:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=3ST0219319000137
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true        

  device_MUENW19214000676:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4773:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=MUENW19214000676
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true        

  device_27d73a060505:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4783:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=27d73a060505
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true       

  device_8C3X1H9U8:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4793:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=8C3X1H9U8
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true  

  device_ce11182b2ba7733002:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4803:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=ce11182b2ba7733002
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true        

  device_2caa0aae17017ece:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4813:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=2caa0aae17017ece
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true        

  device_5200c2a2437d26fb:
    image: nesh/device_with_appium:2.1
          #    image: 09174097ea59
    restart: unless-stopped
    depends_on:
      - selenium_hub
    ports:
      - 4823:4723
    privileged: true
    volumes:
      - ~/.android:/root/.android
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - STF_TOKEN=${STF_TOKEN}
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - REMOTE_ADB=true
      - ANDROID_DEVICES=5200c2a2437d26fb
      - REMOTE_ADB_POLLING_SEC=60
      - RELAXED_SECURITY=true        
